### ISSUE TITLE
What to specify in the appName, companyName and productName?

### ISSUE THREAD

**Issue by alexursul** [alexmercerind/desktoasts#3]
Hi! Thank you for a such great component.
Could you please tell, is it important what I pass to the ToastService(...) via appName, companyName and productName variables?

My application started crashing on startup (when the ToastService is registered) after adding this component, but it doesn't crash every time I start it - only sometimes.
I'm wondering if this could be due to the fact that the information passed to the ToastService is not reliable for Windows?

I tried to run the app with the -v flag, however it's impossible to understand what's wrong with the app:
<pre>
[  +16 ms] 
   #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
   #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:663:9)
   <asynchronous suspension>
   #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
   <asynchronous suspension>
   #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
   <asynchronous suspension>
   #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
   <asynchronous suspension>
   #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
   <asynchronous suspension>
   #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
   <asynchronous suspension>
   #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
   <asynchronous suspension>
   #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
   <asynchronous suspension>
   #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
   <asynchronous suspension>
   #10     main (package:flutter_tools/executable.dart:91:3)
   <asynchronous suspension>
</pre>

**Comment by bdlukaa** [comment]
Could you post the whole logs in a spoiler tag?
